<a href="https://colab.research.google.com/github/PRAVEEN-DIXIT07/Analogwatch/blob/master/scalars_and_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import torch


In [34]:
x_pt = torch.tensor(25)
x_pt

tensor(25)

In [35]:
x_pt.shape

torch.Size([])

In [36]:
import tensorflow as tf

In [37]:
x_tf = tf.Variable(25,dtype = tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [38]:
x_tf.shape

TensorShape([])

In [39]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [40]:
x_tf+y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [41]:
tf_sum = tf.add(x_tf , y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [42]:
tf_sum.numpy()

28

In [43]:
import numpy as np

In [44]:
x = np.array([25,2,5])

In [45]:
len(x)

3

In [46]:
x.shape

(3,)

In [47]:
type(x)

numpy.ndarray

In [48]:
x.dtype

dtype('int64')

In [49]:
x[0]

25

In [50]:
type(x[0])

numpy.int64

In [51]:
x.T

array([25,  2,  5])

In [52]:
y = np.array([[25,2,5]])

In [53]:
y.shape

(1, 3)

In [54]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [55]:
y_t.shape

(3, 1)

In [56]:
#zero vectors
z = np.zeros(3)

In [57]:
z

array([0., 0., 0.])

In [58]:
z.dtype

dtype('float64')

In [59]:
#vectors in tensor flow and pytorch

x_pt = torch.tensor([25,5,2])

In [60]:
x_pt

tensor([25,  5,  2])

In [61]:
x_tf = tf.Variable([25,2,5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>