<a href="https://colab.research.google.com/github/PRAVEEN-DIXIT07/Analogwatch/blob/master/scalars_and_vectors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch


In [3]:
x_pt = torch.tensor(25)
x_pt

tensor(25)

In [4]:
x_pt.shape

torch.Size([])

In [5]:
import tensorflow as tf

In [6]:
x_tf = tf.Variable(25,dtype = tf.int16)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int16, numpy=25>

In [7]:
x_tf.shape

TensorShape([])

In [8]:
y_tf = tf.Variable(3, dtype=tf.int16)

In [9]:
x_tf+y_tf

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [10]:
tf_sum = tf.add(x_tf , y_tf)
tf_sum

<tf.Tensor: shape=(), dtype=int16, numpy=28>

In [11]:
tf_sum.numpy()

28

In [12]:
import numpy as np

In [13]:
x = np.array([25,2,5])

In [14]:
len(x)

3

In [15]:
x.shape

(3,)

In [16]:
type(x)

numpy.ndarray

In [17]:
x.dtype

dtype('int64')

In [18]:
x[0]

25

In [19]:
type(x[0])

numpy.int64

In [20]:
x.T

array([25,  2,  5])

In [21]:
y = np.array([[25,2,5]])

In [22]:
y.shape

(1, 3)

In [24]:
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [25]:
y_t.shape

(3, 1)

In [26]:
#zero vectors
z = np.zeros(3)

In [27]:
z

array([0., 0., 0.])

In [28]:
z.dtype

dtype('float64')

In [29]:
#vectors in tensor flow and pytorch

x_pt = torch.tensor([25,5,2])

In [30]:
x_pt

tensor([25,  5,  2])

In [32]:
x_tf = tf.Variable([25,2,5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5], dtype=int32)>